# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_util.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftest_util.proto\"\x0f\n\rTestUtilEmpty28\n\x0cTestUtilPing\x12(\n\x04Ping\x12\x0e.TestUtilEmpty\x1a\x0e.TestUtilEmpty\"\x00\x62\x06proto3')



_TESTUTILEMPTY = DESCRIPTOR.message_types_by_name['TestUtilEmpty']
TestUtilEmpty = _reflection.GeneratedProtocolMessageType('TestUtilEmpty', (_message.Message,), {
  'DESCRIPTOR' : _TESTUTILEMPTY,
  '__module__' : 'test_util_pb2'
  # @@protoc_insertion_point(class_scope:TestUtilEmpty)
  })
_sym_db.RegisterMessage(TestUtilEmpty)

_TESTUTILPING = DESCRIPTOR.services_by_name['TestUtilPing']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TESTUTILEMPTY._serialized_start=19
  _TESTUTILEMPTY._serialized_end=34
  _TESTUTILPING._serialized_start=36
  _TESTUTILPING._serialized_end=92
# @@protoc_insertion_point(module_scope)
