# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: twophase.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etwophase.proto\"\x12\n\x10GetCommittedArgs\"\x07\n\x05\x45mpty\"<\n\nMaybeValue\x12\x11\n\tavailable\x18\x01 \x01(\x08\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\x05\"\x14\n\x04Vote\x12\x0c\n\x04vote\x18\x01 \x01(\x08\x32|\n\x06Worker\x12\x30\n\x0cGetCommitted\x12\x11.GetCommittedArgs\x1a\x0b.MaybeValue\"\x00\x12!\n\x08SetValue\x12\x0b.MaybeValue\x1a\x06.Empty\"\x00\x12\x1d\n\x04Vote\x12\x0b.MaybeValue\x1a\x06.Empty\"\x00\x32R\n\x0b\x43oordinator\x12!\n\x08SetValue\x12\x0b.MaybeValue\x1a\x06.Empty\"\x00\x12 \n\x07Prepare\x12\x0b.MaybeValue\x1a\x06.Empty\"\x00\x62\x06proto3')



_GETCOMMITTEDARGS = DESCRIPTOR.message_types_by_name['GetCommittedArgs']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_MAYBEVALUE = DESCRIPTOR.message_types_by_name['MaybeValue']
_VOTE = DESCRIPTOR.message_types_by_name['Vote']
GetCommittedArgs = _reflection.GeneratedProtocolMessageType('GetCommittedArgs', (_message.Message,), {
  'DESCRIPTOR' : _GETCOMMITTEDARGS,
  '__module__' : 'twophase_pb2'
  # @@protoc_insertion_point(class_scope:GetCommittedArgs)
  })
_sym_db.RegisterMessage(GetCommittedArgs)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'twophase_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

MaybeValue = _reflection.GeneratedProtocolMessageType('MaybeValue', (_message.Message,), {
  'DESCRIPTOR' : _MAYBEVALUE,
  '__module__' : 'twophase_pb2'
  # @@protoc_insertion_point(class_scope:MaybeValue)
  })
_sym_db.RegisterMessage(MaybeValue)

Vote = _reflection.GeneratedProtocolMessageType('Vote', (_message.Message,), {
  'DESCRIPTOR' : _VOTE,
  '__module__' : 'twophase_pb2'
  # @@protoc_insertion_point(class_scope:Vote)
  })
_sym_db.RegisterMessage(Vote)

_WORKER = DESCRIPTOR.services_by_name['Worker']
_COORDINATOR = DESCRIPTOR.services_by_name['Coordinator']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETCOMMITTEDARGS._serialized_start=18
  _GETCOMMITTEDARGS._serialized_end=36
  _EMPTY._serialized_start=38
  _EMPTY._serialized_end=45
  _MAYBEVALUE._serialized_start=47
  _MAYBEVALUE._serialized_end=107
  _VOTE._serialized_start=109
  _VOTE._serialized_end=129
  _WORKER._serialized_start=131
  _WORKER._serialized_end=255
  _COORDINATOR._serialized_start=257
  _COORDINATOR._serialized_end=339
# @@protoc_insertion_point(module_scope)
